### ISSUE TITLE
How to run function elixirFM ?

### ISSUE THREAD

**Issue by wijananto** [otakar-smrz/elixir-fm#1]
First congratulations for the good work in this Functional Arabic Morphology.
I have installed and compiled [elixir-fm/Haskell/ElixirFM/](https://github.com/otakar-smrz/elixir-fm/tree/master/Haskell/ElixirFM)

```
cabal update
cabal install
```

and just installed perl module [elixir-fm/Perl/ElixirFM/](https://github.com/otakar-smrz/elixir-fm/tree/master/Perl/ElixirFM)

```
perl Build.PL
Build
Build install
```

My Environment System: 
`Ubuntu 14.04 LTS x64bit`, `Perl v5.18.2`, `ghc v7.6.3`, `cabal-install v1.24.0.0` 

What command and How to run ElixirFM like resolve, inflect, derive, and lookup ?
Where to type the command ?

I never use haskell and perl before.

Any chance you could lend a hand?
_-thanks._

**Comment by otakar-smrz** [comment]
Thanks for your interest in ElixirFM!
I have authored some guidance for using ElixirFM from a [Shell command line](http://github.com/otakar-smrz/elixir-fm/blob/master/README.ipynb) or from a [Python interpreter](http://github.com/otakar-smrz/elixir-fm/blob/master/Python/ElixirFM/README.ipynb). 
Please let me know if you need further details.
