### ISSUE TITLE
Python/ElixirFM jupyter notebook no module Encode.Arabic 

### ISSUE THREAD

**Issue by tomas-hartman** [otakar-smrz/elixir-fm#10]
I cannot make python (nor perl) version of ElixirFM running, possibly because of missing `Encode.Arabic`. Should it be automatically installed or should I install it manually from somewhere? There seem to be a growing number of issues due to deprecation of python v2.7, so I am not sure if there's a fault on my side or if it's the deprecation.

<img width="428" alt="obrazek" src="https://user-images.githubusercontent.com/44980733/151264619-d6a7a671-d4b1-4927-a1c5-2019bcdb4bba.png">

I seem to have a problem with encoding in general. When I tried to run some sample code from previous issue, I ran across another encoding-related error:

<img width="955" alt="obrazek" src="https://user-images.githubusercontent.com/44980733/151264914-7afece55-5911-444e-a5b6-d54e876b88f5.png">

Is there a way to make it work?

```
python v2.7.16
Elixir 1.13.2 (compiled with Erlang/OTP 24)
```

**Comment by tomas-hartman** [comment]
Resolved, I found the solution after all.

- The first error seems to be some sort of bug/my misunderstanding of how jupyter notebooks work in vscode. After manually "playing" code for separate lines, it throws error.
- In order to resolve the other one I just added `# -*- coding: utf-8 -*-` to the beginning of my test file, there should be a better solution which I don't know yet.

**Comment by otakar-smrz** [comment]
Thank you for you interest in ElixirFM! Encode Arabic is to be installed from https://github.com/otakar-smrz/encode-arabic.
