### ISSUE TITLE
Export to SQL

### ISSUE THREAD

**Issue by fajaryanw** [otakar-smrz/elixir-fm#3]
Is ElixirFM data can be export to SQL ? 
If yes, How to export in SQL ?
I really appreciate your help
Thanks

**Comment by otakar-smrz** [comment]
There is no direct support for converting data to SQL. ElixirFM output can be turned into JSON, though:
https://github.com/otakar-smrz/elixir-fm/blob/master/Python/ElixirFM/README.ipynb
